import type { DashboardData } from './types';

const summary = {
  carriedOverPositions: 24,
  carriedOverRequests: 8,
  newRequestPositions: 28,
  newRequestRequests: 12,
  totalWorkloadPositions: 52,
  totalWorkloadRequests: 20,
  filledPositionsThisPeriod: 24,
  filledPositionsFromOldRequests: 6,
  filledPositionsFromCurrentMonthRequests: 18,
  fullyClosedPositionsThisPeriod: 18,
  fullyClosedRequestsThisPeriod: 9,
  partialRequests: 4,
  partialPositions: 11,
  cancelledPositionsThisPeriod: 3,
  cancelledRequestsThisPeriod: 2,
  remainingPositions: 25,
  remainingRequests: 11,
  endingBacklogPositions: 25,
  endingBacklogRequests: 11,
  startingBacklogPositions: 24,
  netBacklogChange: 1,
  resignationRequestPositions: 18,
  fillRatePercent: 46.2,
  fullCloseRatePercent: 45,
  fullClosureRatePercent: 45,
  backlogBurnRatePercent: 25,
  newDemandAbsorptionRatePercent: 64.3,
  resignationPressureRatio: 34.6,
  dataQualityMode: 'event_based' as const,
  fulfilledRequestsTouchedThisPeriod: 12,
  resolvedRequestsThisPeriod: 11,
  resolutionRatePercent: 55,
  cancellationRatePercent: 5.8,
};

const flowView = {
  startingBacklogPositions: 24,
  newRequestPositions: 28,
  totalWorkloadPositions: 52,
  filledPositions: 24,
  cancelledPositions: 3,
  endingBacklogPositions: 25,
  netBacklogChange: 1,
};

const demoWorkItem = {
  id: 'demo-1',
  requestNo: 'RQ-240701',
  unitName: 'ศูนย์การค้าเซ็นทรัล',
  destination: 'กรุงเทพฯ',
  ownerName: 'สมหญิง ใจดี',
  screenerName: '—',
  status: 'overdue' as const,
  slaStatus: 'breached' as const,
  priority: 0,
  requestDate: '2026-07-01',
  requiredDate: '2026-07-05',
  updatedAt: '2026-07-01',
  nextAction: 'ติดตามด่วน',
  requestAction: 'ลาออก',
  sendReplacement: true,
  resignedName: 'นาย ก.',
  isResignation: true,
  requestPositions: 5,
  filledPositions: 2,
  cancelledPositions: 0,
  remainingPositions: 3,
  effectiveRequestDate: '2026-07-05',
  slaDueDate: '2026-07-20',
  daysOverdue: 5,
  lifecycleKind: 'ลาออก',
  requestKind: 'ฉุกเฉิน',
  controlStatus: 'Partial Closed / ยังไม่จบ',
};

/** Demo payload when API feed is empty (local dev / offline). */
export const MOCK_DASHBOARD_DATA: DashboardData = {
  periodLabel: 'เดือนนี้',
  previousPeriodLabel: 'เดือนที่แล้ว',
  activityTrendLabel: 'ม.ค. 2026 – ก.ค. 2026',
  kpis: [
    { id: 'total_requests', label: 'ใบขอทั้งหมด', value: 52, secondaryCount: 20, secondaryLabel: 'ใบขอ', description: '52 ตำแหน่ง · 20 ใบขอ', trendPercent: null },
    { id: 'closed', label: 'ปิดใบขอ', value: 24, secondaryCount: 12, secondaryLabel: 'ใบขอที่มีการหาได้', description: 'หาได้แล้ว · 24 ตำแหน่ง', trendPercent: null },
    { id: 'cancelled', label: 'ยกเลิก', value: 3, secondaryCount: 2, secondaryLabel: 'ใบขอ', description: '3 ตำแหน่ง · 2 ใบขอ', trendPercent: null },
    { id: 'remaining', label: 'คงเหลือ', value: 25, secondaryCount: 11, secondaryLabel: 'ใบขอ', description: '25 ตำแหน่ง · 11 ใบขอ', trendPercent: null },
  ],
  workStatusKpis: [
    { id: 'work_status_total', label: 'ทั้งหมด', value: 25, secondaryCount: 20, secondaryLabel: 'ใบขอ', description: 'ผลรวมสถานะ = 25 อัตรา · 20 ใบ', trendPercent: null },
    { id: 'work_status_in_progress', label: 'กำลังดำเนินการสรรหา', value: 10, secondaryCount: 9, secondaryLabel: 'ใบขอ', description: '10 อัตรา · 9 ใบ', trendPercent: null },
    { id: 'work_status_evaluating', label: 'เริ่มประเมิน', value: 3, secondaryCount: 2, secondaryLabel: 'ใบขอ', description: '3 อัตรา · 2 ใบ', trendPercent: null },
    { id: 'work_status_waiting_inform', label: 'รอแจ้งเข้า', value: 4, secondaryCount: 3, secondaryLabel: 'ใบขอ', description: '4 อัตรา · 3 ใบ', trendPercent: null },
    { id: 'work_status_waiting_interview', label: 'รอสัมภาษณ์', value: 5, secondaryCount: 4, secondaryLabel: 'ใบขอ', description: '5 อัตรา · 4 ใบ', trendPercent: null },
    { id: 'work_status_waiting_start', label: 'รอเริ่มงาน/รอผลสัมภาษณ์', value: 3, secondaryCount: 2, secondaryLabel: 'ใบขอ', description: '3 อัตรา · 2 ใบ', trendPercent: null },
  ],
  requestControlSummary: summary,
  flowView,
  executiveInsights: {
    sentences: [
      'งานค้างเพิ่มขึ้น 1 ตำแหน่ง เทียบต้นงวด',
      'ใบขอลาออกคิดเป็น 34.6% ของความต้องการรวมเดือนนี้',
      'ทีมหาได้แล้ว 24 ตำแหน่ง แต่ปิดครบใบขอได้เพียง 9 ใบ',
      'การหางานค้างเก่าช่วย 25% ของการหาได้ในงวดนี้',
      'หน่วยงานที่เกิน SLA มากที่สุด: ศูนย์การค้าเซ็นทรัล (2 ใบ)',
    ],
    slaHighlights: [{ kind: 'unit' as const, name: 'ศูนย์การค้าเซ็นทรัล', breachCount: 2 }],
  },
  requestCohortSummary: {
    rows: [
      { id: 'backlog_from_previous_period', label: 'ยอดค้างจากงวดก่อน', requestPositions: 24, requestCount: 8, filledPositions: 10, remainingPositions: 14, fullyClosedRequests: 3, partialRequests: 2, cancelledRequests: 1 },
      { id: 'new_this_period', label: 'ขอใหม่งวดนี้', requestPositions: 28, requestCount: 12, filledPositions: 14, remainingPositions: 14, fullyClosedRequests: 6, partialRequests: 2, cancelledRequests: 1 },
      { id: 'total', label: 'รวมภาระงาน', requestPositions: 52, requestCount: 20, filledPositions: 24, remainingPositions: 28, fullyClosedRequests: 9, partialRequests: 4, cancelledRequests: 2 },
    ],
  },
  fulfillmentBreakdown: { filledSamePeriod: 18, filledBacklog: 6, fullyClosedSamePeriod: 6, fullyClosedBacklog: 3 },
  closedBreakdown: { samePeriod: 18, backlog: 6 },
  slaSummary: { onTrack: 12, atRisk: 4, breached: 3, closedOnTime: 7, closedLate: 2, breachRatePercent: 20 },
  lifecycleInsights: ['% ลาออกต่อใบขอรวม 34.6%', 'ปิดได้เยอะ แต่ปิดครบใบขอยังน้อย — มี Partial ค้าง'],
  activityTrend: [
    { date: '2026-01-01', label: 'ม.ค.', resignations: 6, replacements: 4, newOpenings: 9, increaseHeadcount: 5, newSite: 4, requestedPositions: 22, closedPositions: 18, filledPositions: 18 },
    { date: '2026-02-01', label: 'ก.พ.', resignations: 7, replacements: 5, newOpenings: 10, increaseHeadcount: 6, newSite: 4, requestedPositions: 24, closedPositions: 20, filledPositions: 20 },
    { date: '2026-07-01', label: 'ก.ค.', resignations: 4, replacements: 3, newOpenings: 6, increaseHeadcount: 3, newSite: 3, requestedPositions: 14, closedPositions: 11, filledPositions: 11 },
  ],
  unitOverview: [
    { name: 'ธนาคารกรุงศรี', total: 18, open: 9, overdue: 2, sharePercent: 34.6 },
    { name: 'ศูนย์การค้าเซ็นทรัล', total: 14, open: 6, overdue: 1, sharePercent: 26.9 },
    { name: 'ไทยพาณิชย์ สำนักงานใหญ่', total: 11, open: 4, overdue: 0, sharePercent: 21.2 },
  ],
    ageDaysBreakdown: [
    { bucket: 'advance', label: 'ล่วงหน้า', count: 22 },
    { bucket: '1-7', label: '1–7 วัน', count: 18 },
    { bucket: '8-15', label: '8–15 วัน', count: 11 },
    { bucket: '16-30', label: '16–30 วัน', count: 9 },
    { bucket: '30+', label: '30 วันขึ้นไป', count: 4 },
  ],
  ageDaysPositionTotal: 52,
  ageDaysRequestTotal: 48,
  recruiterOverview: [
    { name: 'สมหญิง ใจดี', role: 'recruiter', total: 14, completed: 8, remaining: 6, sharePercent: 29.2 },
    { name: 'วิชัย รักงาน', role: 'recruiter', total: 11, completed: 6, remaining: 5, sharePercent: 22.9 },
    { name: 'อรทัย คัดสรร', role: 'screener', total: 12, completed: 7, remaining: 5, sharePercent: 26.1 },
  ],
  workQueue: [demoWorkItem],
  priorityWorkQueue: [demoWorkItem],
};
